# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_NAME = "symbols/ubuntu-docker"
MEMORY = "512"
MANAGERS = 2
MANAGER_IP = ["192.168.33.2", "192.168.33.3"]
WORKERS = 2
WORKER_IP = ["192.168.33.4", "192.168.33.5"]
CPUS = 2
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    #Common setup
    config.vm.box = BOX_NAME
    config.vm.synced_folder ".", "/vagrant"
    config.vm.provider "vmware_desktop" do |vb|
      vb.memory = MEMORY
      vb.cpus = CPUS
    end
    #Setup Manager Nodes
    (1..MANAGERS).each do |i|
        config.vm.define "manager0#{i}" do |manager|
          manager.vm.network :private_network, ip: MANAGER_IP[i-1]
          manager.vm.hostname = "manager0#{i}"
          if i == 1  # Server Manager đầu tiên của Docker Swarm
            #Only configure port to host for Manager01
            manager.vm.network :forwarded_port, guest: 8080, host: 8080
            manager.vm.network :forwarded_port, guest: 5000, host: 5000
            manager.vm.network :forwarded_port, guest: 9000, host: 9000
          end
        end
    end
    #Setup Woker Nodes
    (1..WORKERS).each do |i|
        config.vm.define "worker0#{i}" do |worker|
            worker.vm.network :private_network, ip: WORKER_IP[i-1]
            worker.vm.hostname = "worker0#{i}"
        end
    end
end