# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
BOX_NAME = "symbols/ubuntu-docker"
PROVIDER = "vmware_desktop"  # "virtualbox"
MEMORY = "512"
CPUS = 2

MANAGERS = 2
MANAGER_IP = ["192.168.33.2", "192.168.33.3"]
WORKERS = 1
WORKER_IP = ["192.168.33.4"]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    #Common setup
    config.vm.box = BOX_NAME
    config.vm.synced_folder "./src", "/src"
    config.vm.provider PROVIDER do |vb|
      vb.memory = MEMORY
      vb.cpus = CPUS
    end
    #Setup Manager Nodes
    (1..MANAGERS).each do |i|
        config.vm.define "manager0#{i}" do |manager|
          manager.vm.network :private_network, ip: MANAGER_IP[i-1]
          manager.vm.hostname = "manager0#{i}"
          if i == 1  # Server Manager đầu tiên của Docker Swarm      
            manager.vm.network :forwarded_port, guest: 9000, host: 9000
            manager.vm.network :forwarded_port, guest: 8080, host: 8080
            manager.vm.network :forwarded_port, guest: 8000, host: 8000
            manager.vm.network :forwarded_port, guest: 8001, host: 8001
            manager.vm.network :forwarded_port, guest: 8002, host: 8002
            manager.vm.network :forwarded_port, guest: 5000, host: 5000
            manager.vm.network :forwarded_port, guest: 5432, host: 5432
            manager.vm.network :forwarded_port, guest: 6379, host: 6379
          end
        end
    end
    #Setup Woker Nodes
    (1..WORKERS).each do |i|
        config.vm.define "worker0#{i}" do |worker|
            worker.vm.network :private_network, ip: WORKER_IP[i-1]
            worker.vm.hostname = "worker0#{i}"
        end
    end
end