# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"
  config.vm.provider "vmware_desktop" do |vm|
    vm.vmx['displayname'] = "Ubuntu Docker"
    vm.gui = false 
    vm.memory = "2048"
    vm.cpus = 2    
  end
  
  config.vm.provision "shell",inline: $install_docker_script, privileged: true
end

$install_docker_script = <<SCRIPT
echo "Installing dependencies ..."
sudo apt-get update
echo Installing Docker...
apt install -y docker.io
sudo usermod -aG docker vagrant
SCRIPT