# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"
  config.vm.provider "vmware_desktop" do |vm|
    vm.vmx['displayname'] = "Ubuntu Nginx"
    vm.gui = false  
    vm.memory = "2048"
    vm.cpus = 2    
  end
  config.vm.network "forwarded_port", guest: 80, host: 9000
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "./homepage", "/var/www/html"
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y nginx
  SHELL
end
